services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: bankuser
      POSTGRES_PASSWORD: bankpass
      POSTGRES_DB: bankdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bankuser -d bankdb"]
      interval: 3s
      timeout: 3s
      retries: 20
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://bankuser:bankpass@db:5432/bankdb?schema=public
      PORT: 3000
      LOG_LEVEL: info
      IDEMPOTENCY_TTL_SECONDS: 86400
      SEED_ON_START: "1"
    ports:
      - "3001:3000"
    command: ["./scripts/wait-for.sh", "db", "--", "node", "dist/server.js"]

volumes:
  db_data:
